Repository wahanegi/vibereport, pull requests merged in 2023-02, with the labels that each got.

#1 CI-9
  .gitignore
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/assets/config/manifest.js
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/application.js
  app/javascript/controllers/index.js
  app/views/layouts/application.html.erb
  bin/bundle
  bin/dev
  bin/importmap
  config/application.rb
  config/credentials.yml.enc
  config/importmap.rb
  config/initializers/assets.rb
  config/routes.rb
  lib/tasks/auto_annotate_models.rake
  package.json
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/test_helper.rb
  yarn.lock
Labels: review done, testing done

#3 CI-12: Create a README
  Gemfile.lock
  README.md
Labels: review needed

#4 CI-13: Added MIT License to README
  README.md
Labels: review done, testing done

#5 CI-16: Add CodeClimate integration
  .codeclimate.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
Labels: in testing, review needed

#2 CI-19: Set up models for sending Emotion Selection email
  .gitignore
  Gemfile
  Gemfile.lock
  app/admin/admin_users.rb
  app/admin/dashboard.rb
  app/admin/emotions.rb
  app/admin/time_periods.rb
  app/admin/users.rb
  app/assets/javascripts/active_admin.js
  app/assets/stylesheets/active_admin.scss
  app/helpers/emotions_helper.rb
  app/helpers/user_email_mailer_helper.rb
  app/mailers/user_email_mailer.rb
  app/models/admin_user.rb
  app/models/emotion.rb
  app/models/time_period.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/user_email_mailer/response_invite.html.erb
  app/workers/emotion_selection_notification_worker.rb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/active_admin.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20230213134506_devise_create_users.rb
  db/migrate/20230213151147_create_emotions.rb
  db/migrate/20230213164537_create_time_periods.rb
  db/migrate/20230221055527_devise_create_admin_users.rb
  db/migrate/20230221055528_create_active_admin_comments.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/emotion_selection_notification.rake
  package.json
  spec/factories/admin_users.rb
  spec/factories/emotions.rb
  spec/factories/time_periods.rb
  spec/factories/users.rb
  spec/helpers/user_email_mailer_helper_spec.rb
  spec/mailers/previews/user_email_preview.rb
  spec/mailers/user_email_spec.rb
  spec/models/admin_user_spec.rb
  spec/models/emotion_spec.rb
  spec/models/time_period_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/admin/admin_users_spec.rb
  spec/requests/admin/emotion_spec.rb
  spec/requests/admin/time_period_spec.rb
  spec/requests/admin/users_spec.rb
  spec/spec_helper.rb
  spec/workers/emotion_selection_notification_worker_spec.rb
Labels: review done

#6 CI-14: HerokuCI config file
  app.json
Labels: testing done, review needed
