Repository wahanegi/vibereport, pull requests merged in 2023-03, with the labels that each got.

#12 CI-14: Get spin-up servers to automatically run migrations and seed the database
  Procfile
  app.json
  config/environments/development.rb
  config/environments/production.rb
  db/seeds.rb
  db/seeds/starting_emotions.yml
Labels: review done

#8 CI-34: Login
  Gemfile
  Gemfile.lock
  app/admin/passwordless_sessions.rb
  app/admin/users.rb
  app/assets/config/manifest.js
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/logo.scss
  app/assets/stylesheets/main.scss
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  app/helpers/home_helper.rb
  app/javascript/application.js
  app/models/user.rb
  app/views/home/app.html.erb
  app/views/layouts/application.html.erb
  app/views/passwordless/mailer/magic_link.html.erb
  app/views/passwordless/mailer/magic_link.text.erb
  app/views/passwordless/sessions/create.html.erb
  app/views/passwordless/sessions/new.html.erb
  config/initializers/passwordless.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230221134211_create_passwordless_sessions.passwordless.rb
  db/schema.rb
  package.json
  spec/helpers/home_helper_spec.rb
  spec/models/time_period_spec.rb
  spec/requests/home_spec.rb
  spec/requests/react_spec.rb
  yarn.lock
Labels: review done, ready for testing

#13 CI-73: User cant be updated from Active Admin
  app/admin/users.rb
  spec/requests/admin/users_spec.rb
Labels: review done

#14 CI-96: Unnecessary Dashboard Log-in link is present on Access Site page
  app/views/passwordless/sessions/new.html.erb
Labels: review done, testing done

#16 CI-106: The "Email" field has wrong width on Access Site page
  app/assets/stylesheets/main.scss
Labels: review done, testing done

#17 CI-105: Line breaks are absent for the “If you have any issues..”
  app/views/passwordless/sessions/create.html.erb
Labels: review done, testing done

#28 CI-9: Configure Postmarkapp to work with production
  Gemfile
  Gemfile.lock
  config/environments/production.rb
Labels: review needed
