Repository wahanegi/vibereport, pull requests merged in 2023-04, with the labels that each got.

#22 CI-83: Meme Selection
  .gitignore
  Gemfile.lock
  app/assets/images/edit-pencil.svg
  app/assets/images/help.svg
  app/assets/images/logo.svg
  app/assets/images/shoutout-large.svg
  app/assets/images/shoutout-small.svg
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/application.css
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/colors.scss
  app/assets/stylesheets/fonts.scss
  app/assets/stylesheets/gif.scss
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/swal.scss
  app/controllers/api/v1/emotions_controller.rb
  app/controllers/api/v1/responses_controller.rb
  app/javascript/components/Pages/EmotionIntensity.js
  app/javascript/components/Pages/FollowUpPosMeme.js
  app/javascript/components/Pages/FollowUpPosWordOnly.js
  app/javascript/components/Pages/Gifs/GifItem.js
  app/javascript/components/Pages/Gifs/GifList.js
  app/javascript/components/Pages/Gifs/SearchBar.js
  app/javascript/components/Pages/Gifs/index.js
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/Pages/MemeSelection.js
  app/javascript/components/Pages/OwnMemeUploadFollow.js
  app/javascript/components/Pages/ProductivityCheckLow.js
  app/javascript/components/Pages/Results.js
  app/javascript/components/Pages/SelectedGIPHYFollow.js
  app/javascript/components/ResponseFlow.js
  app/javascript/components/UI/BackButton.js
  app/javascript/components/UI/Menu.js
  app/javascript/components/UI/NavigationButtons.js
  app/javascript/components/UI/QuestionButton.js
  app/javascript/components/UI/ShareContent.js
  app/javascript/components/UI/ShoutoutButton.js
  app/javascript/components/__tests__/ListEmotions.test.js
  app/javascript/components/__tests__/MemeSelection.test.js
  app/javascript/components/helpers/consts.js
  app/javascript/components/helpers/helper.js
  app/javascript/components/helpers/helpers.js
  app/javascript/components/helpers/routes.js
  app/models/response.rb
  app/serializers/response_serializer.rb
  app/views/passwordless/sessions/create.html.erb
  app/views/passwordless/sessions/new.html.erb
  config/environments/development.rb
  db/migrate/20230314222428_add_gif_url_to_response.rb
  db/schema.rb
  jest.config.js
  package.json
  spec/factories/responses.rb
  spec/models/response_spec.rb
  spec/requests/emotions_spec.rb
  spec/requests/responses_spec.rb
  svgTransform.js
  yarn.lock
Labels: review done, testing done

#26 CI-109: Update the "from" field
  app.json
  config/environments/development.rb
Labels: review done, testing done

#31 CI-122: Style improvements for web pages
  app/assets/fonts/Qw3aZQNVED7rKGKxtqIqX5EUDXx4.woff2
  app/assets/images/calendar.png
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/colors.scss
  app/assets/stylesheets/design_system_vibereport.scss
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/variables.scss
  app/javascript/components/UI/NavigationButtons.js
  app/javascript/components/UI/ShareContent.js
  app/javascript/components/UI/ShoutoutButton.js
  package.json
Labels: review done

#25 CI-100: Emotion Intensity
  .gitignore
  Gemfile.lock
  app/assets/images/PoweredBy.svg
  app/assets/stylesheets/gif.scss
  app/assets/stylesheets/main.scss
  app/controllers/api/v1/responses_controller.rb
  app/javascript/components/Pages/EmotionIntensity.js
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/Pages/MemeSelection.js
  app/javascript/components/Pages/SelectedGIPHYFollow.js
  app/javascript/components/UI/ShareContent.js
  app/javascript/components/__tests__/ListEmotions.test.js
  app/javascript/components/helpers/consts.js
  app/models/response.rb
  app/serializers/response_serializer.rb
  db/migrate/20230320153827_add_rating_to_responses.rb
  db/schema.rb
  package.json
  spec/factories/responses.rb
  spec/models/response_spec.rb
  spec/requests/responses_spec.rb
  yarn.lock
Labels: review done, testing done

#21 CI-71: Displaying of the current week dates does not match the specs in Emotion Selection Email
  app.json
  app/admin/time_periods.rb
  app/assets/stylesheets/email_page.css
  app/controllers/api/v1/emotions_controller.rb
  app/javascript/components/Pages/ListEmotions.js
  app/mailers/user_email_mailer.rb
  app/models/time_period.rb
  app/workers/emotion_selection_notification_worker.rb
  config/environments/development.rb
  db/migrate/20230407183434_add_due_date_to_time_periods.rb
  db/schema.rb
  spec/factories/time_periods.rb
  spec/models/time_period_spec.rb
Labels: testing done

#33 CI-154: The design of the Meme Selection page doesn't match the specs
  Gemfile.lock
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/colors.scss
  app/assets/stylesheets/gif.scss
  app/javascript/components/Pages/Gifs/GifItem.js
  app/javascript/components/Pages/Gifs/index.js
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/Pages/MemeSelection.js
  app/javascript/components/UI/Menu.js
  app/javascript/components/UI/ShareContent.js
Labels: review done, testing done

#35 CI-156: The user is redirected to the top of the Giphy search
  app/javascript/components/Pages/Gifs/SearchResults.js
  app/javascript/components/Pages/Gifs/index.js
Labels: review done, testing done

#30 CI-114: Productivity Check
  app/admin/responses.rb
  app/assets/images/flame10.svg
  app/assets/images/flame2.svg
  app/assets/images/flame3.svg
  app/assets/images/flame4.svg
  app/assets/images/flame5.svg
  app/assets/images/flame6.svg
  app/assets/images/flame7.svg
  app/assets/images/flame8.svg
  app/assets/images/flame9.svg
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/main.scss
  app/controllers/api/v1/responses_controller.rb
  app/javascript/components/Pages/EmotionIntensity.js
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/Pages/MemeSelection.js
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/javascript/components/Pages/ProductivityCheckLow.js
  app/javascript/components/ResponseFlow.js
  app/javascript/components/__tests__/ProductivityCheckLow.test.js
  app/javascript/components/helpers/consts.js
  app/javascript/components/helpers/routes.js
  app/models/response.rb
  app/serializers/response_serializer.rb
  db/migrate/20230329093246_add_productivity_to_responses.rb
  db/schema.rb
  spec/factories/responses.rb
  spec/models/response_spec.rb
  spec/requests/responses_spec.rb
Labels: review done, testing done

#39 CI-157: The "Next" button is disabled when going back after entering
  app/views/passwordless/sessions/new.html.erb
  config/environments/production.rb
Labels: review done, testing done

#40 CI-158: The "Help" and "Shout" buttons are not fully displayed when zoom <=80%
  app/assets/stylesheets/main.scss
  app/javascript/components/UI/QuestionButton.js
  app/javascript/components/UI/ShoutoutButton.js
Labels: review done, testing done

#44 CI-170: The "Excellent choice!" text color doesn't match specs on Selected Giphy Follow page
  app/assets/stylesheets/design_system_vibereport.scss
  app/javascript/components/Pages/EmotionIntensity.js
Labels: review done, testing done

#38 CI-42: Emotion Entry
  Gemfile.lock
  app/admin/emotions.rb
  app/assets/images/icon_negative.svg
  app/assets/images/icon_neutral.svg
  app/assets/images/icon_positive.svg
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/colors.scss
  app/assets/stylesheets/emition_entry.scss
  app/assets/stylesheets/main.scss
  app/controllers/api/v1/emotions_controller.rb
  app/javascript/components/Pages/EmotionEntry.js
  app/javascript/components/requests/axios_requests.js
  app/models/emotion.rb
  app/models/response.rb
  app/serializers/emotion_serializer.rb
  app/serializers/response_serializer.rb
  config/environments/development.rb
  config/routes.rb
  db/migrate/20230331084242_add_public_to_emotions.rb
  db/schema.rb
  db/seeds.rb
  package.json
  spec/factories/emotions.rb
  spec/factories/responses.rb
  spec/models/emotion_spec.rb
  spec/models/response_spec.rb
  spec/requests/emotions_spec.rb
  spec/requests/responses_spec.rb
  yarn.lock
Labels: review done, testing done

#42 CI-125: Productivity Follow-up
  Gemfile.lock
  app/admin/responses.rb
  app/assets/stylesheets/gif.scss
  app/assets/stylesheets/main.scss
  app/controllers/api/v1/responses_controller.rb
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/models/response.rb
  app/serializers/response_serializer.rb
  db/migrate/20230413202440_add_bad_follow_comment_to_response.rb
  db/schema.rb
  spec/factories/responses.rb
  spec/models/response_spec.rb
  spec/requests/responses_spec.rb
Labels: review done, testing done

#32 CI-131: Celebrate
  app/admin/responses.rb
  app/assets/stylesheets/design_system_vibereport.scss
  app/assets/stylesheets/main.scss
  app/controllers/api/v1/emotions_controller.rb
  app/controllers/api/v1/responses_controller.rb
  app/javascript/components/Pages/CausesToCelebrate.js
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/javascript/components/Pages/ProductivityCheckLow.js
  app/javascript/components/UI/ShareContent.js
  app/javascript/components/UI/mention/mentionsInputStyles.js
  app/javascript/components/__tests__/CausesToCelebrate.test.js
  app/javascript/components/__tests__/ProductivityBadFollowUp.test.js
  app/models/response.rb
  app/models/time_period.rb
  app/models/user.rb
  app/serializers/response_serializer.rb
  app/workers/emotion_selection_notification_worker.rb
  db/migrate/20230404160406_add_celebrate_comment_to_response.rb
  db/schema.rb
  package.json
  spec/factories/responses.rb
  spec/models/response_spec.rb
  spec/models/time_period_spec.rb
  spec/models/user_spec.rb
  spec/requests/emotions_spec.rb
  spec/requests/responses_spec.rb
  yarn.lock
Labels: review done, testing done

#50 CI-219: Users are not redirected on Celebrate page from the Productivity Follow-up page.
  app/javascript/components/Pages/ProductivityBadFollowUp.js
Labels: review done, testing done

#43 CI-171: Sometimes the Emotion word bubbles are not located in appropriate emotion categories
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/main.scss
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/UI/ButtonEmotion.js
  app/javascript/components/helpers/library.js
Labels: review done, testing done

#49 CI-216: Dropdown list run over text after entering the "@" symbol into the field on Celebrate page
  app/javascript/components/UI/mention/mentionsInputStyles.js
Labels: review done, testing done
