Repository wahanegi/vibereport, pull requests merged in 2023-08, with the labels that each got.

#125 CI-496: [Gmail]The content on the Emotion Selection/Magic link/Results/Reminder emails doesn't meet the specs
  app/assets/images/logo.png
  app/assets/stylesheets/email_page.css
  app/javascript/components/UI/Logo.js
  app/views/layouts/_logo.erb
  config/initializers/active_admin.rb
Labels: review done, testing done

#127 CI-499: The calendar icon is absent on Emotion Selection Web
  app/assets/stylesheets/email_page.css
  app/javascript/components/Pages/ListEmotions.js
Labels: review done, testing done

#129 CI-501: The user is redirected to Emotion Selection Web page after clicking any button in Emotion Selection Email
  app/controllers/api/v1/responses_controller.rb
  app/mailers/user_email_mailer.rb
  app/services/api/v1/response_flow_from_email.rb
  spec/services/api/v1/response_flow_from_email_spec.rb
Labels: review done, testing done

#128 CI-500: Modify conditions for creating Due Dates in Active Admin
  app/models/time_period.rb
  app/workers/emotion_selection_notification_worker.rb
  config/environments/development.rb
  spec/factories/time_periods.rb
  spec/models/time_period_spec.rb
  spec/workers/emotion_selection_notification_worker_spec.rb
Labels: review done, testing done

#132 CI-505: Change the verbiage on the Emotion Selection Email/Emotion Selection Web
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/__tests__/ListEmotions.test.js
  app/views/user_email_mailer/response_invite.html.erb
Labels: review done, testing done

#131 CI-506: Change the verbiage on the Emotion Entry/Emotion Type pages
  app/javascript/components/UI/ToggleEmotionType.js
Labels: review done, testing done

#130 CI-507: Remove the expansion and contraction feature in the Icebreaker section on the Results page
  app/assets/stylesheets/results.scss
  app/javascript/components/Pages/ResultsPage/QuestionSection.js
Labels: review done, testing done

#133 CI-504: Adjustments to the productivity verbatims
  app/admin/dashboard.rb
  app/admin/responses.rb
  app/controllers/api/v1/responses_controller.rb
  app/helpers/active_admin_helpers.rb
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/javascript/components/__tests__/ListEmotions.test.js
  app/javascript/components/__tests__/ProductivityBadFollowUp.test.js
  app/models/response.rb
  app/reports/productivity_verbatims.rb
  app/serializers/response_serializer.rb
  db/migrate/20230807151155_rename_bad_follow_comment_to_productivity_comment.rb
  db/schema.rb
  spec/factories/responses.rb
  spec/models/response_spec.rb
  spec/reports/productivity_verbatims_spec.rb
  spec/requests/responses_spec.rb
Labels: review done, testing done

#135 CI-508: Add hover tooltip over selected meme on the Results page
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/gif.scss
  app/javascript/components/Pages/ResultsPage/GifSection.js
  app/presenters/api/v1/results_presenter.rb
  package.json
  spec/presenters/results_presenter_spec.rb
  yarn.lock
Labels: review done, testing done

#136 CI-509: Remove the expansion and contraction feature in the Shoutouts section on the Results page
  app/javascript/components/Pages/ResultsPage/ShoutoutItem.js
Labels: review done, testing done

#137 CI-512: Add the ability to edit Icebreaker answer on the Results page
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/results.scss
  app/controllers/api/v1/fun_question_answers_controller.rb
  app/javascript/components/Pages/ResultsPage/QuestionSection.js
  app/javascript/components/Pages/ResultsPage/index.js
  app/presenters/api/v1/results_presenter.rb
  spec/presenters/results_presenter_spec.rb
  spec/requests/fun_question_answers_spec.rb
Labels: review done, testing done

#140 CI-513: Icebreaker answers from the current time period are displayed in the previous time period
  app/javascript/components/Pages/ResultsPage/QuestionSection.js
Labels: review done, testing done

#139 CI-510: Change the design of the Results email
  app/assets/images/cloud_words.png
  app/views/user_email_mailer/results_email.html.erb
Labels: review done, testing done

#138 CI-498: The content on the Emotion Selection/Magic link/Results/Reminder emails doesn't meet the specs in Gmail/Outlook
  app/assets/stylesheets/email_page.css
  app/views/layouts/_logo.erb
  app/views/user_email_mailer/reminder_email.html.erb
  app/views/user_email_mailer/response_invite.html.erb
  app/views/user_email_mailer/results_email.html.erb
Labels: review done, testing done

#142 CI-517: The users are not redirected to their ‘Results’ page for the corresponding check-in period after clicking the "See the Results" button on the Results email.
  app/controllers/api/v1/emotions_controller.rb
  app/javascript/components/Pages/ResultsPage/QuestionSection.js
Labels: review done, testing done

#141 CI-515: Make it possible for users to add emojis to the Shoutout answers on the Results page
  app/assets/images/chevron-left.svg
  app/assets/images/chevron-right.svg
  app/assets/images/reshot-icon-grinning.svg
  app/assets/images/reshot-icon-smile.svg
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/results.scss
  app/controllers/api/v1/emojis_controller.rb
  app/javascript/components/Pages/ResultsPage/Emojis/EmojiPicker.js
  app/javascript/components/Pages/ResultsPage/Emojis/EmojiRow.js
  app/javascript/components/Pages/ResultsPage/Emojis/ShowEmojis.js
  app/javascript/components/Pages/ResultsPage/QuestionSection.js
  app/javascript/components/Pages/ResultsPage/ShoutoutItem.js
  app/javascript/components/Pages/ResultsPage/ShoutoutSection.js
  app/javascript/components/Pages/ResultsPage/index.js
  app/javascript/components/helpers/consts.js
  app/javascript/components/helpers/helpers.js
  app/models/emoji.rb
  app/models/fun_question_answer.rb
  app/models/shoutout.rb
  app/models/user.rb
  app/presenters/api/v1/results_presenter.rb
  config/routes.rb
  db/migrate/20230811175143_create_emoji_table.rb
  db/schema.rb
  package.json
  spec/factories/emojis.rb
  spec/models/emoji_spec.rb
  spec/presenters/results_presenter_spec.rb
  spec/requests/emojis_spec.rb
  yarn.lock
Labels: review done, testing done, requires DB migrations

#145 CI-520: The user is redirected to a blank page after clicking the "See the Results" button on the Results email.
  app/javascript/components/Pages/ResultsPage/ResultsPreview.js
Labels: review done, testing done

#143 CI-514: Create easy way in ActiveAdmin to generate nag emails.
  app/admin/dashboard.rb
  app/admin/responses.rb
  app/assets/stylesheets/active_admin.scss
  app/assets/stylesheets/main.scss
  app/controllers/api/v1/users_controller.rb
  app/helpers/active_admin_helpers.rb
  app/helpers/application_helper.rb
  app/mailers/user_email_mailer.rb
  app/views/user_email_mailer/send_reminder.html.erb
  config/routes.rb
  spec/requests/users_spec.rb
Labels: review done, testing done

#134 [Snyk] Security upgrade stimulus-rails from 1.2.1 to 1.2.2
  Gemfile
  Gemfile.lock
Labels: review done, testing done

#147 [Snyk] Security upgrade puma from 5.6.5 to 5.6.7
  Gemfile
  Gemfile.lock
Labels: review done, testing done

#149 CI-522: The blank page is opened after clicking the "Edit response" button on the Results page if user clicked "Rather not to say" button on the Emotion Selection email
  app/javascript/components/Pages/ResultsPage/NavigationBar.js
Labels: review done, testing done

#89 [Snyk] Security upgrade @babel/preset-env from 7.21.5 to 7.22.6
  package.json
  yarn.lock
Labels: review done, testing done

#151 CI-523: Remove the Selected Giphy Follow page
  app/javascript/components/Pages/MemeSelection.js
  app/javascript/components/Pages/SelectedGIPHYFollow.js
  app/javascript/components/ResponseFlow.js
  app/javascript/components/helpers/routes.js
Labels: review done, testing done

#152 CI-526: Change the color of the emotion words in the word cloud to blue on the Results page
  app/javascript/components/Pages/ResultsPage/EmotionSection.js
Labels: review done, testing done

#144 CI-511: Remove the option to tag team members on the Celebrate page
  app/admin/celebrate_shoutouts.rb
  app/admin/responses.rb
  app/admin/time_periods.rb
  app/admin/users.rb
  app/controllers/api/v1/emotions_controller.rb
  app/controllers/api/v1/responses_controller.rb
  app/controllers/api/v1/shoutouts_controller.rb
  app/javascript/components/Pages/CausesToCelebrate.js
  app/javascript/components/Pages/ResultsPage/ShoutoutItem.js
  app/javascript/components/Pages/modals/CelebrateModal.js
  app/javascript/components/UI/mention/mentionsInputStyles.js
  app/models/response.rb
  app/reports/celebration_verbatims.rb
  app/reports/celebrations_count.rb
  app/serializers/response_serializer.rb
  app/workers/migrate_shoutouts_worker.rb
  db/migrate/20230815135714_add_celebrate_comment_to_responses.rb
  db/schema.rb
  lib/tasks/migrate_celebrate_shoutouts.rake
  package.json
  spec/factories/responses.rb
  spec/models/response_spec.rb
  spec/requests/responses_spec.rb
  spec/workers/migrate_shoutouts_worker_spec.rb
  yarn.lock
Labels: review done, testing done, requires DB migrations, requires run rake task

#146 CI-516: Add the ability for user to designate a Shoutout as public or private
  app/admin/shoutouts.rb
  app/assets/images/icon_private.svg
  app/assets/images/icon_public.svg
  app/assets/stylesheets/colors.scss
  app/assets/stylesheets/main.scss
  app/controllers/api/v1/shoutouts_controller.rb
  app/javascript/components/Pages/ResultsPage/ShoutoutSection.js
  app/javascript/components/Pages/ResultsPage/index.js
  app/javascript/components/UI/ShoutoutModal.js
  app/javascript/components/UI/SwitcherShoutouts.js
  app/javascript/components/UI/rich-text/RichInputElement.js
  app/javascript/components/__tests__/RichInputElement.test.js
  app/models/celebrate_shoutout.rb
  app/models/shoutout.rb
  app/presenters/api/v1/results_presenter.rb
  app/serializers/shoutout_serializer.rb
  db/migrate/20230816075429_add_public_to_shoutouts.rb
  db/migrate/20230825130700_update_existing_shoutouts_to_false.rb
  db/schema.rb
  spec/controllers/shoutouts_controller_spec.rb
  spec/factories/celebrate_shoutouts.rb
  spec/factories/shoutouts.rb
  spec/models/celebrate_shoutout_spec.rb
  spec/models/shoutout_spec.rb
  spec/presenters/results_presenter_spec.rb
Labels: review done, testing done, requires DB migrations

#148 CI-518: Add the ability to upload own gifs directly to the GIPHY Api on the Meme selection page
  app/javascript/components/Pages/Gifs/GifList.js
  app/javascript/components/Pages/Gifs/SearchResults.js
  app/javascript/components/Pages/Gifs/index.js
  app/javascript/components/Pages/MemeSelection.js
  app/javascript/components/Pages/ResultsPage/GifSection.js
  app/javascript/components/UI/ProgressBar.js
  app/javascript/components/helpers/consts.js
  app/javascript/components/helpers/helpers.js
  package.json
  spec/requests/emotions_spec.rb
  yarn.lock
Labels: review done, testing done

#154 CI-532: The user is redirected to a blank page after clicking the "See the Results" button on the Results email.
  app/javascript/components/Pages/ResultsPage/ResultsPreview.js
  app/presenters/api/v1/results_presenter.rb
Labels: review done, testing done
