Repository wahanegi/vibereport, pull requests merged in 2025-02, with the labels that each got.

#237 VIB-13: Refactor Update Recognition for mobile-friendly layout
  app/assets/stylesheets/design_system_vibereport.scss
  app/assets/stylesheets/main.scss
  app/javascript/components/Pages/Recognition.js
  app/javascript/components/UI/BlockLowerBtns.js
  app/javascript/components/UI/rich-text/DropDownList.js
  app/javascript/components/UI/rich-text/ListItem.js
  app/javascript/components/UI/rich-text/RichInputElement.js
  app/javascript/components/UI/rich-text/RichTextArea.js
Labels: review done

#225 VIB-11: Refactor Productivity Check for mobile-friendly layout
  app/assets/stylesheets/icebreaker_answer.scss
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/typography.scss
  app/javascript/components/Pages/CausesToCelebrate.js
  app/javascript/components/Pages/EmotionEntry.js
  app/javascript/components/Pages/EmotionIntensity.js
  app/javascript/components/Pages/EmotionType.js
  app/javascript/components/Pages/IcebreakerAnswer.js
  app/javascript/components/Pages/IcebreakerQuestion.js
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/javascript/components/Pages/ProductivityCheckLow.js
  app/javascript/components/Pages/Recognition.js
  app/javascript/components/UI/BlockLowerBtns.js
Labels: review done, qa done

#224 VIB-9: Refactor Meme Selection for mobile-friendly layout
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/design_system_vibereport.scss
  app/assets/stylesheets/gif.scss
  app/javascript/components/Pages/Gifs/GifList.js
  app/javascript/components/Pages/Gifs/SearchBar.js
  app/javascript/components/Pages/Gifs/index.js
  app/javascript/components/Pages/MemeSelection.js
  app/javascript/components/UI/ShareContent.js
Labels: review done, qa done

#220 VIB-31: Fix Rubocop Autocorrectable Offenses in the Codebase
  app/admin/dashboard.rb
  app/admin/fun_question.rb
  app/admin/fun_question_answer.rb
  app/admin/responses.rb
  app/admin/teams.rb
  app/admin/time_periods.rb
  app/admin/user_teams.rb
  app/admin/users.rb
  app/controllers/api/v1/fun_question_answers_controller.rb
  app/controllers/devise/passwordless/sessions_controller.rb
  app/helpers/active_admin_helpers.rb
  app/models/fun_question.rb
  app/models/fun_question_answer.rb
  app/models/notification.rb
  app/models/shoutout.rb
  app/models/user_team.rb
  app/presenters/api/v1/results_presenter.rb
  app/reports/teammate_engagement_count.rb
  app/reports/teammate_engagement_verbatims.rb
  config/environments/production.rb
  config/initializers/assets.rb
  config/initializers/premailer_rails.rb
  config/routes.rb
  db/migrate/20230221055527_devise_create_admin_users.rb
  db/migrate/20230221134211_create_passwordless_sessions.passwordless.rb
  db/migrate/20230824175454_add_manager_to_users.rb
  db/seeds.rb
  lib/tasks/auto_annotate_models.rake
  spec/admin/teams_spec.rb
  spec/controllers/shoutouts_controller_spec.rb
  spec/factories/emojis.rb
  spec/helpers/emotions_helper_spec.rb
  spec/helpers/user_email_mailer_helper_spec.rb
  spec/mailers/user_email_spec.rb
  spec/models/emoji_spec.rb
  spec/models/emotion_spec.rb
  spec/models/time_period_spec.rb
  spec/models/user_spec.rb
  spec/presenters/results_presenter_spec.rb
  spec/rails_helper.rb
  spec/reports/emotion_index_spec.rb
  spec/services/api/v1/response_flow_from_email_spec.rb
  spec/spec_helper.rb
Labels: review done

#214 VIB-26: Upgrade axios from 1.6.0 to 1.7.4
  app/admin/dashboard.rb
  app/admin/fun_question.rb
  app/admin/fun_question_answer.rb
  app/admin/responses.rb
  app/admin/teams.rb
  app/admin/time_periods.rb
  app/admin/user_teams.rb
  app/admin/users.rb
  app/controllers/api/v1/fun_question_answers_controller.rb
  app/controllers/devise/passwordless/sessions_controller.rb
  app/helpers/active_admin_helpers.rb
  app/models/fun_question.rb
  app/models/fun_question_answer.rb
  app/models/notification.rb
  app/models/shoutout.rb
  app/models/user_team.rb
  app/presenters/api/v1/results_presenter.rb
  app/reports/teammate_engagement_count.rb
  app/reports/teammate_engagement_verbatims.rb
  config/environments/production.rb
  config/initializers/assets.rb
  config/initializers/premailer_rails.rb
  config/routes.rb
  db/migrate/20230221055527_devise_create_admin_users.rb
  db/migrate/20230221134211_create_passwordless_sessions.passwordless.rb
  db/migrate/20230824175454_add_manager_to_users.rb
  db/seeds.rb
  lib/tasks/auto_annotate_models.rake
  package.json
  spec/admin/teams_spec.rb
  spec/controllers/shoutouts_controller_spec.rb
  spec/factories/emojis.rb
  spec/helpers/emotions_helper_spec.rb
  spec/helpers/user_email_mailer_helper_spec.rb
  spec/mailers/user_email_spec.rb
  spec/models/emoji_spec.rb
  spec/models/emotion_spec.rb
  spec/models/time_period_spec.rb
  spec/models/user_spec.rb
  spec/presenters/results_presenter_spec.rb
  spec/rails_helper.rb
  spec/reports/emotion_index_spec.rb
  spec/services/api/v1/response_flow_from_email_spec.rb
  spec/spec_helper.rb
  yarn.lock
Labels: review done, qa done

#244 VIB-21 Refactor mailers views
  app/assets/stylesheets/email_page.css
  app/controllers/api/v1/users_controller.rb
  app/mailers/user_email_mailer.rb
  app/views/devise/mailer/magic_link.html.erb
  app/views/user_email_mailer/auto_remind_checkin.html.erb
  app/views/user_email_mailer/reminder_email.html.erb
  app/views/user_email_mailer/response_invite.html.erb
  app/views/user_email_mailer/results_email.html.erb
  app/views/user_email_mailer/send_reminder.html.erb
Labels: review done

#245 VIB-18: Final Review - Remove Unused CSS Files and Classes
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/colors.scss
  app/assets/stylesheets/design_system_vibereport.scss
  app/assets/stylesheets/email_page.css
  app/assets/stylesheets/emition_entry.scss
  app/assets/stylesheets/gif.scss
  app/assets/stylesheets/icebreaker_answer.scss
  app/assets/stylesheets/logo.scss
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/mixins.scss
  app/assets/stylesheets/results.scss
  app/assets/stylesheets/typography.scss
  app/assets/stylesheets/variables.scss
  app/javascript/components/Header.js
  app/javascript/components/Pages/CheckInClosed.js
  app/javascript/components/Pages/EmotionEntry.js
  app/javascript/components/Pages/EmotionIntensity.js
  app/javascript/components/Pages/EmotionType.js
  app/javascript/components/Pages/IcebreakerAnswer.js
  app/javascript/components/Pages/IcebreakerQuestion.js
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/javascript/components/Pages/RatherNotSay/RatherNotSay.js
  app/javascript/components/Pages/RatherNotSay/SkipAhead.js
  app/javascript/components/Pages/Recognition.js
  app/javascript/components/Pages/ResultsPage/Emojis/EmojiPicker.js
  app/javascript/components/Pages/ResultsPage/Emojis/ShowEmojis.js
  app/javascript/components/Pages/ResultsPage/EmotionSection.js
  app/javascript/components/Pages/ResultsPage/GifSection.js
  app/javascript/components/Pages/ResultsPage/ShoutoutAwards.js
  app/javascript/components/Pages/ResultsPage/ShoutoutSection.js
  app/javascript/components/Pages/modals/HelpModal.js
  app/javascript/components/Pages/modals/ShoutoutModal.js
  app/javascript/components/Pages/modals/WorkingModal.js
  app/javascript/components/UI/Input.js
  app/javascript/components/UI/Menu.js
  app/javascript/components/UI/ShareContent.js
  app/javascript/components/UI/SwitcherShoutouts.js
  app/javascript/components/UI/ToggleEmotionType.js
  app/javascript/components/UI/modal/MessageYesNoOk.js
  app/javascript/components/UI/rich-text/RichInputElement.js
  app/views/devise/sessions/new.html.erb
  app/views/home/sent.html.erb
  app/views/layouts/_help_modal.erb
Labels: review done

#217 VIB-24 Upgrade Ruby on Rails
  Gemfile
  Gemfile.lock
  README.md
  app/models/fun_question_answer.rb
  app/models/notification.rb
  config/database.yml
  db/schema.rb
Labels: review done, qa done

#241 VIB-38: Magic Link email is not received after entering email address with a capital first letter on Sign_in page
  app.json
  app/controllers/devise/passwordless/sessions_controller.rb
Labels: review done, qa done

#239 VIB-30: Add description to Productivity step
  app/javascript/components/Pages/ProductivityCheckLow.js
  app/javascript/components/helpers/helpers.js
Labels: review done, qa done

#247 VIB-50: Create Project model for storing synced data from Google Sheet or Exce
  app.json
  app/admin/projects.rb
  app/models/project.rb
  db/migrate/20250207121456_create_projects.rb
  db/schema.rb
  spec/factories/projects.rb
  spec/models/project_spec.rb
Labels: review done, qa done

#251 VIB-72: Removal of the Help Button from the Main Flow
  app/assets/images/help.svg
  app/assets/stylesheets/main.scss
  app/javascript/components/Pages/CheckInClosed.js
  app/javascript/components/Pages/ResultsPage/index.js
  app/javascript/components/Pages/ResultsPageManager/index.js
  app/javascript/components/Pages/modals/HelpModal.js
  app/javascript/components/Pages/modals/SweetAlertHelp.js
  app/javascript/components/UI/CornerElements.js
  app/javascript/components/UI/QuestionButton.js
  app/javascript/components/UI/ShareContent.js
  app/views/devise/sessions/new.html.erb
  app/views/home/sent.html.erb
  app/views/layouts/_help_modal.erb
Labels: review done, qa done

#260 VIB-83: The Header background color does not meet the specifications on all application pages for the logged-in user
  app/javascript/components/Header.js
  app/javascript/components/UI/Menu.js
Labels: review done, qa done

#252 VIB-73: Removed 'Notifications' from ActiveAdmin
  app/admin/dashboard.rb
  app/admin/notifications.rb
  app/controllers/api/v1/notifications_controller.rb
  app/models/notification.rb
  app/models/user.rb
  config/routes.rb
  spec/factories/notifications.rb
  spec/models/notification_spec.rb
  spec/requests/notifications_spec.rb
Labels: review done, qa done

#255 VIB-77: Update Footer Layout
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/results.scss
  app/javascript/components/UI/ShoutoutButton.js
  app/views/home/sent.html.erb
Labels: review done, qa done

#248 VIB-47: Enable Timesheet Entry for a Team in ActiveAdmin
  app/admin/teams.rb
  app/assets/stylesheets/active_admin.scss
  app/models/team.rb
  db/migrate/20250212134705_add_timesheet_enabled_to_teams.rb
  db/schema.rb
  spec/factories/teams.rb
  spec/models/team_spec.rb
Labels: review done, qa done

#259 VIB-56 Submit button does not work on icebreaker-question page when entering question that already exists in database
  app/javascript/components/Pages/IcebreakerQuestion.js
  app/javascript/components/requests/axios_requests.js
Labels: review done, qa done

#268 VIB-71: Removal of Help Button Functionality
  app/admin/dashboard.rb
  app/admin/notifications.rb
  app/assets/images/help.svg
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/results.scss
  app/controllers/api/v1/notifications_controller.rb
  app/javascript/components/Pages/CheckInClosed.js
  app/javascript/components/Pages/ResultsPage/index.js
  app/javascript/components/Pages/ResultsPageManager/index.js
  app/javascript/components/Pages/modals/HelpModal.js
  app/javascript/components/Pages/modals/SweetAlertHelp.js
  app/javascript/components/UI/CornerElements.js
  app/javascript/components/UI/QuestionButton.js
  app/javascript/components/UI/ShareContent.js
  app/javascript/components/UI/ShoutoutButton.js
  app/models/notification.rb
  app/models/user.rb
  app/views/devise/sessions/new.html.erb
  app/views/home/sent.html.erb
  app/views/layouts/_help_modal.erb
  config/routes.rb
  db/migrate/20250214101305_drop_notifications.rb
  db/schema.rb
  spec/factories/notifications.rb
  spec/models/notification_spec.rb
  spec/requests/notifications_spec.rb
Labels: review done, requires DB migrations, qa done

#264 VIB-85: The design of the sign_in page does not meet the specifications for not logged-in user
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/main.scss
  app/views/devise/sessions/new.html.erb
Labels: review done, qa done

#269 VIB-89: The design of the icebreaker-answer page does not meet the specifications for the web view
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/main.scss
  app/javascript/components/Pages/CausesToCelebrate.js
  app/javascript/components/Pages/EmotionEntry.js
  app/javascript/components/Pages/EmotionIntensity.js
  app/javascript/components/Pages/EmotionType.js
  app/javascript/components/Pages/IcebreakerAnswer.js
  app/javascript/components/Pages/IcebreakerQuestion.js
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/javascript/components/Pages/ProductivityCheckLow.js
  app/javascript/components/Pages/Recognition.js
  app/javascript/components/UI/BlockLowerBtns.js
  app/javascript/components/UI/ShareContent.js
Labels: review done, qa done

#267 VIB-91: The layout is not unified on each page of the application for the web view
  app/assets/stylesheets/design_system_vibereport.scss
  app/assets/stylesheets/main.scss
  app/javascript/components/Footer.js
  app/javascript/components/Header.js
  app/javascript/components/Layout.js
  app/javascript/components/Pages/CausesToCelebrate.js
  app/javascript/components/Pages/EmotionIntensity.js
  app/javascript/components/Pages/EmotionType.js
  app/javascript/components/Pages/MemeSelection.js
  app/javascript/components/Pages/Recognition.js
  app/javascript/components/UI/ButtonEmotion.js
  app/javascript/components/UI/Menu.js
Labels: review done, qa done

#262 VIB-62: Create the DropdownSelect Component
  app/assets/images/complete50.svg
  app/assets/images/complete50_act.svg
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/dropdown_select.scss
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/javascript/components/Pages/ProductivityCheckLow.js
  app/javascript/components/Pages/TimesheetPage.js
  app/javascript/components/ResponseFlow.js
  app/javascript/components/UI/DropdownSelect.js
  app/javascript/components/UI/Menu.js
  app/javascript/components/helpers/routes.js
  package.json
  yarn.lock
Labels: review done, qa done

#253 VIB-52: Create TimeSheetEntry Model
  app/admin/time_sheet_entry.rb
  app/models/project.rb
  app/models/time_period.rb
  app/models/time_sheet_entry.rb
  app/models/user.rb
  db/migrate/20250210062915_create_time_sheet_entries.rb
  spec/factories/time_sheet_entries.rb
  spec/models/project_spec.rb
  spec/models/time_period_spec.rb
  spec/models/time_sheet_entry_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: review done, qa done

#273 VIB-88: The dropdown list with coworkers doesn't match specs on Recognition page after entering @ symbol in a modal
  app/assets/stylesheets/main.scss
  app/javascript/components/Pages/modals/ShoutoutModal.js
  app/javascript/components/UI/SwitcherShoutouts.js
  app/javascript/components/UI/rich-text/DropDownList.js
  app/javascript/components/UI/rich-text/RichInputElement.js
  app/javascript/components/UI/rich-text/RichTextArea.js
  app/javascript/components/UI/rich-text/cursor.js
Labels: review done, qa done

#271 VIB-86: The design of the sent page does not meet the specifications for not logged-in user
  app/controllers/devise/passwordless/sessions_controller.rb
  app/controllers/home_controller.rb
  app/views/home/sent.html.erb
Labels: review done, qa done

#261 VIB-81: Create API Endpoint for Fetching Project Data
  app/controllers/api/v1/projects_controller.rb
  app/serializers/project_serializer.rb
  config/routes.rb
  spec/requests/projects_spec.rb
Labels: review done, qa done

#257 VIB-51: Email Timesheet Entry Results for last time period
  app/mailers/time_sheet_mailer.rb
  app/views/time_sheet_mailer/time_sheet_results_email.html.erb
  app/workers/time_sheet_results_email_worker.rb
  lib/tasks/time_sheet_results_notification.rake
  spec/mailers/previews/time_sheet_mailer_preview.rb
  spec/mailers/time_sheet_mailer_spec.rb
Labels: review done, qa done

#263 VIB-80: Correct how weeks are shown (part of Make changes to database)
  app/controllers/api/v1/emotions_controller.rb
  app/javascript/components/helpers/helpers.js
  app/models/time_period.rb
  spec/models/time_period_spec.rb
Labels: review done, qa done

#266 VIB-90: The design of the Сauses-to-celebrate page does not meet the specifications for the web view
  app/assets/stylesheets/main.scss
  app/javascript/components/Pages/CausesToCelebrate.js
  app/javascript/components/Pages/ProductivityBadFollowUp.js
  app/javascript/components/Pages/modals/ShoutoutModal.js
Labels: review done, qa done

#275 VIB-84: The design of the recognition page does not meet the specifications for the logged-in user
  app/assets/stylesheets/main.scss
  app/javascript/components/Footer.js
  app/javascript/components/Pages/Recognition.js
  app/javascript/components/UI/ShoutoutButton.js
Labels: review done, qa done

#265 VIB-55: Add soft deletion to Project model (part of Make changes to database)
  app/admin/projects.rb
  app/controllers/api/v1/projects_controller.rb
  app/models/project.rb
  db/migrate/20250214101806_add_deleted_at_to_projects.rb
  db/schema.rb
  spec/admin/projects_spec.rb
  spec/factories/projects.rb
  spec/models/project_spec.rb
  spec/requests/projects_spec.rb
Labels: review done, qa done

#276 VIB-63: Create the TimesheetRow Component (part of Create Timesheet page)
  app/assets/images/timesheet-row-delete.svg
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/timesheet_row.scss
  app/javascript/components/UI/DropdownSelect.js
  app/javascript/components/UI/TimesheetRow.js
Labels: review done, qa done

#238 VIB-36: Add new metrics to Teams view page (Part of Changes to Team Metrics epic)
  app/admin/dashboard.rb
  app/admin/teams.rb
  app/assets/javascripts/active_admin.js
  app/assets/stylesheets/active_admin.scss
  app/helpers/active_admin_helpers.rb
  app/models/time_period.rb
  app/presenters/api/v1/results_presenter.rb
  app/reports/admin_report.rb
  app/reports/celebration_verbatims.rb
  app/reports/celebrations_count.rb
  app/reports/emotion_index.rb
  app/reports/participation_percentage.rb
  app/reports/productivity_average.rb
  app/reports/responses_report.rb
  app/reports/shoutout_author_report.rb
  app/reports/shoutouts_count_report.rb
  app/reports/teammate_engagement_count.rb
  app/reports/teammate_engagement_verbatims.rb
  spec/models/time_period_spec.rb
  spec/reports/participation_percentage_spec.rb
  spec/workers/remind_check_in_email_worker_spec.rb
Labels: review done, qa done

#236 VIB-35: Remove unnecessary metrics (Part of Changes to Team Metrics epic)
  app/admin/dashboard.rb
  app/admin/teams.rb
  app/helpers/active_admin_helpers.rb
Labels: review done, qa done

#282 VIB-94: Word bubbles do not adjust for long emotion words on the Emotion-selection page using app in the tablet and mobile views
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/design_system_vibereport.scss
  app/assets/stylesheets/main.scss
  app/javascript/components/Footer.js
  app/javascript/components/Pages/ListEmotions.js
  app/javascript/components/Pages/ResultsPage/GifSection.js
  app/javascript/components/UI/ButtonEmotion.js
  app/javascript/components/UI/ShoutoutButton.js
Labels: review done, qa done

#272 VIB-92: Remove or fix "Comments" tab from Active Admin
  app/admin/teams.rb
  config/initializers/active_admin.rb
  db/migrate/20250221120414_drop_active_admin_comments.rb
  db/schema.rb
Labels: review done, requires DB migrations, qa done

#280 VIB-34: Changes to Team Metrics
  app/admin/dashboard.rb
  app/admin/teams.rb
  app/assets/javascripts/active_admin.js
  app/assets/stylesheets/active_admin.scss
  app/helpers/active_admin_helpers.rb
  app/models/time_period.rb
  app/presenters/api/v1/results_presenter.rb
  app/reports/admin_report.rb
  app/reports/celebration_verbatims.rb
  app/reports/celebrations_count.rb
  app/reports/emotion_index.rb
  app/reports/participation_percentage.rb
  app/reports/productivity_average.rb
  app/reports/responses_report.rb
  app/reports/shoutout_author_report.rb
  app/reports/shoutouts_count_report.rb
  app/reports/teammate_engagement_count.rb
  app/reports/teammate_engagement_verbatims.rb
  spec/models/time_period_spec.rb
  spec/reports/participation_percentage_spec.rb
  spec/workers/remind_check_in_email_worker_spec.rb
Labels: review done, qa done

#283 VIB-64: Create the TimesheetForm Component (part of Create Timesheet page)
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/dropdown_select.scss
  app/assets/stylesheets/timesheet_row.scss
  app/assets/stylesheets/timesheetpage.scss
  app/javascript/components/Pages/ResultsPage/NavigationBar.js
  app/javascript/components/Pages/TimesheetPage.js
  app/javascript/components/UI/Button.js
  app/javascript/components/UI/DropdownSelect.js
  app/javascript/components/UI/ShareContent.js
  app/javascript/components/UI/TimesheetRow.js
  app/javascript/components/UI/TimesheetRowHeader.js
Labels: review done, qa done
